Update README.md
Looks like firebase now requires logging in and an initialization step. (Probably would be good to indicate what options to select when initializing too!) 

```
➜ firebase use --add

Error: Failed to authenticate, have you run firebase login?
```

```
➜ firebase use --add

Error: firebase use must be run from a Firebase project directory.

Run firebase init to start a project directory in the current folder.
```